#!/bin/bash
su decodedadmin -c 'sudo pip install virtualenv' && \
virtualenv -p $(which python) env && \
source env/bin/activate && \
pip install jupyter numpy pandas matplotlib && \
jupyter notebook
