#!/bin/bash
su -c 'sudo pip install virtualenv' decodedadmin && \
virtualenv -p $(which python) env && \
source env/bin/activate && \
pip install jupyter numpy pandas matplotlib && \
jupyter notebook
